### ISSUE TITLE
Initialize React Project Structure

### ISSUE THREAD

**Issue by VedantKCSE** [Team-Anonymou5/Tech-Warriors#1]
- [ ] Set up a new React project using Create React App.
- [ ] Install necessary dependencies, including React Router and Material-UI (MUI).
- [ ] Configure ESLint and Prettier for code formatting and linting.
- [ ] Create a basic folder structure with components, pages, and assets directories.
- [ ] Set up the initial configuration for Firebase to retrieve event information.
- [ ] Implement a simple navigation bar and footer using MUI components.
- [ ] Ensure the project is set up for future scalability and ease of maintenance.

**Comment by cyberpvn7** [comment]
Hey vedant,
Assign me this issue
